### ISSUE TITLE
Null reference exception when entire input string is null during string.RemoveStopWords()

### ISSUE THREAD

**Issue by Nixon-Joseph** [hklemp/dotnet-stop-words#1]
In this code, the line with the linq => `s = s.Split(..... ` If the entire input string of 's' is stop words (e.g. 'cannot find'), then the Aggregate call returns null, so it throws an exception on the .ToString().

```
private static string Remove(string s,string shortLanguageName)
		{
			var stopWordList = StopWords.GetStopWords(shortLanguageName);
			s = s.Split(' ').Where(x => !stopWordList.Contains(x)).DefaultIfEmpty().Aggregate((current, next) => current + " " + next).ToString();
			return s;
		}
```

**Comment by hklemp** [comment]
Hi, thanks for the hint.
This is fixed in the new release 1.0.3.
